[flake8]
format = pylint
exclude = .svc,CVS,.bzr,.hg,.git,__pycache__,venv
max-line-length = 120

[pep8]
max-line-length = 120

[mypy]
check_untyped_defs = true
disallow_untyped_defs = true
ignore_errors = true


[mypy-cartography.intel.aws.dynamodb]
ignore_errors = false

[mypy-cartography.intel.aws.ecr]
ignore_errors = false

[mypy-cartography.intel.aws.eks]

[mypy-cartography.intel.aws.elasticsearch]
ignore_errors = false

[mypy-cartography.intel.aws.emr]
ignore_errors = false

[mypy-cartography.intel.aws.iam]
ignore_errors = false

[mypy-cartography.intel.aws.kms]
ignore_errors = false

[mypy-cartography.intel.aws.lambda_function]
ignore_errors = false

[mypy-cartography.intel.aws.organizations]
ignore_errors = false

[mypy-cartography.intel.aws.rds]
ignore_errors = false

[mypy-cartography.intel.aws.redshift]

[mypy-cartography.intel.aws.permission_relationships]
ignore_errors = false

[mypy-cartography.intel.aws.resourcegroupstaggingapi]
ignore_errors = false

[mypy-cartography.intel.aws.resources]
ignore_errors = false

[mypy-cartography.intel.aws.route53]
ignore_errors = false

[mypy-cartography.intel.aws.s3]
ignore_errors = false

[mypy-cartography.intel.aws.ec2.vpc]
ignore_errors = false

[mypy-cartography.intel.aws.ec2.vpc_peering]
ignore_errors = false

[mypy-cartography.intel.aws.ec2.tgw]
ignore_errors = false

[mypy-cartography.intel.aws.ec2.util]
ignore_errors = false

[mypy-cartography.intel.aws.ec2.subnets]
ignore_errors = false

[mypy-cartography.intel.aws.ec2.key_pairs]
ignore_errors = false

[mypy-cartography.intel.aws.util.*]
ignore_errors = false
